apiVersion: v1
kind: Service
metadata:
  labels:
  k8s-app: k8s_python_sample_code
  name: k8s_python_sample_code
  namespace: k8s_python_sample_code
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    TargetPort: 3113
  selector:
  k8s-app: k8s_python_sample_code
